title: Maak en voeg tags toe aan GameObjects
hero_image: images/banner.png
description: Maak en voeg tags toe aan GameObjects
version: 4
listed: false
copyedit: false
last_tested: "2021-11-17"
steps:
  - 
    title: Maak en voeg tags toe aan GameObjects
