title: Create and add tags to GameObjects
hero_image: images/banner.png
description: Create and add tags to GameObjects
version: 4
listed: false
copyedit: false
last_tested: "2021-11-17"
steps:
  - title: Create and add tags to GameObjects
 
